# Please see the README.md for instructions as to how to use and customize.

# NOTE: This file does not build! No dockerfiles are set. See the README.md in this directory.
---
version: '3.8'
services:

  redis:
    image: redis
    hostname : redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
      
  db:
    image: postgres
    hostname : pg
    restart: always
    environment:
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      
  web:
    image: registry.cn-hangzhou.aliyuncs.com/yinweiwen/public/demoweb:latest
    hostname : web
    restart: always
    environment:
      FS_UNIAPP_API: http://api:14000
    ports:
      - "8080:8080"
    depends_on:
      - api
      
  api:
    image: registry.cn-hangzhou.aliyuncs.com/yinweiwen/public/demoapi:latest
    hostname : api
    restart: always
    command: node server.js -p 14000
    environment:
      FS_UNIAPP_DB: postgres://postgres:123@pg:5432/demo
      FS_UNIAPP_FC_LOCAL_SVR_ORIGIN: http://localhost:14000
    ports:
      - "14000:14000"


networks:
  default:
    name: default_network

volumes:
  pgdata:
  redisdata:
