name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.2.0
      with:
        # Version Spec of the version to use. Examples: 12.x, 10.15.1, >=10.15.0.
        node-version: v16.14.2
    - name: compile
      run: cd api && npm install
    - name: compile web
      run: cd web && npm install
    - name: Build the Docker API
      run: cd api && docker build . --file Dockerfile --tag api:$(date +%s)
    - name: Build the Docker WEB
      run: cd web && docker build . --file Dockerfile --tag web:$(date +%s)
