name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.2.0
      with:
        # Version Spec of the version to use. Examples: 12.x, 10.15.1, >=10.15.0.
        node-version: v16.14.2
    - name: compile
      run: cd api && npm install
    - name: compile web
      run: cd web && npm install --legacy-peer-deps
    - name: docker login
      run: docker login --username=yww3571373 --password=${{ secrets.ALI_DOCKER_CREDENTIALS }} registry.cn-hangzhou.aliyuncs.com
    - name: gen version
      id: version
      run: echo '$(date +%s)'
    - name: Build the Docker API
      run: cd api && docker build . --file Dockerfile --tag registry.cn-hangzhou.aliyuncs.com/yinweiwen/public/demoapi:${{ version }}
    - name: Build the Docker WEB
      run: cd web && docker build . --file Dockerfile --tag registry.cn-hangzhou.aliyuncs.com/yinweiwen/public/demoweb:${{ version }}
    - name: publish API
      run: docker push registry.cn-hangzhou.aliyuncs.com/yinweiwen/public/demoapi:${{ version }}
    - name: publish WEB
      run: docker push registry.cn-hangzhou.aliyuncs.com/yinweiwen/public/demoweb:${{ version }}
    - name: Latest API
      run: docker tag registry.cn-hangzhou.aliyuncs.com/yinweiwen/public/demoapi:${{ version }} registry.cn-hangzhou.aliyuncs.com/yinweiwen/public/demoapi:latest && docker push registry.cn-hangzhou.aliyuncs.com/yinweiwen/public/demoapi:latest
    - name: Latest WEB
      run: docker tag registry.cn-hangzhou.aliyuncs.com/yinweiwen/public/demoweb:${{ version }} registry.cn-hangzhou.aliyuncs.com/yinweiwen/public/demoweb:latest && docker push registry.cn-hangzhou.aliyuncs.com/yinweiwen/public/demoweb:latest
